"""File classifier — categorises every file in the repository.

Categories:
  SOURCE      — production source code
  TEST        — test files (must not distort quality metrics)
  GENERATED   — auto-generated code (migrations, schemas, clients)
  VENDOR      — third-party code checked in
  BUILD       — build artifacts, compiled output
  CONFIG      — configuration files
  DOCS        — documentation
  MIGRATION   — database migrations
  ASSET       — binary / static assets
  UNKNOWN     — could not be classified

Rules are applied in order; first match wins.
Every rule documents its rationale.
"""

from __future__ import annotations
import re
from dataclasses import dataclass
from enum import Enum
from typing import NamedTuple


class FileCategory(str, Enum):
    SOURCE    = "source"
    TEST      = "test"
    GENERATED = "generated"
    VENDOR    = "vendor"
    BUILD     = "build"
    CONFIG    = "config"
    DOCS      = "docs"
    MIGRATION = "migration"
    ASSET     = "asset"
    UNKNOWN   = "unknown"


@dataclass(frozen=True)
class ClassifiedFile:
    path:     str
    category: FileCategory
    reason:   str   # why this category was assigned


class FileClassifier:
    """Classifies repository file paths into categories."""

    # ── Vendor / third-party directories ─────────────────────────────────────
    _VENDOR_DIRS = {
        "node_modules", "vendor", "third_party", "thirdparty",
        ".venv", "venv", "env", ".env",
        "bower_components", "jspm_packages",
    }

    # ── Build / artifact directories ─────────────────────────────────────────
    _BUILD_DIRS = {
        "dist", "build", "out", "target", "bin", "obj",
        "__pycache__", ".pytest_cache", ".mypy_cache",
        "coverage", ".coverage", "htmlcov",
        ".next", ".nuxt", ".svelte-kit",
        "site-packages",
    }

    # ── VCS / IDE directories ─────────────────────────────────────────────────
    _SKIP_DIRS = {
        ".git", ".github", ".gitlab", ".svn",
        ".idea", ".vscode", ".vs",
    }

    # ── Test path patterns ────────────────────────────────────────────────────
    _TEST_PATH_RE = re.compile(
        r"(^|/)("
        r"tests?/|__tests__/|test/|spec/|specs/|"
        r"e2e/|integration/|unit/|"
        r"fixtures?/|mocks?/|stubs?/|fakes?/"
        r")",
        re.IGNORECASE,
    )
    _TEST_FILE_RE = re.compile(
        r"(^|/)(test_[^/]+|[^/]+_test|[^/]+\.test\.|[^/]+\.spec\.|"
        r"[^/]+_spec\.|conftest\.|setup_tests?\.)([^/]*)$",
        re.IGNORECASE,
    )

    # ── Generated file patterns ───────────────────────────────────────────────
    _GENERATED_COMMENT_RE = re.compile(
        r"(generated by|do not edit|auto.?generated|"
        r"this file was automatically generated|"
        r"code generated by|generated code)",
        re.IGNORECASE,
    )
    _GENERATED_PATH_RE = re.compile(
        r"(^|/)(generated/|gen/|auto_generated/|pb2\.py$|"
        r"[^/]+\.pb\.go$|[^/]+_pb2\.|[^/]+\.generated\.|"
        r"swagger_client/|openapi_client/|grpc_generated/)",
        re.IGNORECASE,
    )
    _GENERATED_FILENAMES = {
        "schema_pb2.py", "schema_pb2_grpc.py",
    }

    # ── Migration patterns ────────────────────────────────────────────────────
    _MIGRATION_PATH_RE = re.compile(
        r"(^|/)(migrations?/|alembic/|flyway/|liquibase/|"
        r"db/migrate/|database/migrations?/)",
        re.IGNORECASE,
    )
    _MIGRATION_FILE_RE = re.compile(
        r"^\d{4,14}[_\-].+\.(py|sql|rb)$",
        re.IGNORECASE,
    )

    # ── Config / lock files ───────────────────────────────────────────────────
    _CONFIG_EXTENSIONS = {
        ".yaml", ".yml", ".toml", ".ini", ".cfg", ".conf",
        ".json", ".env", ".properties",
    }
    _CONFIG_FILENAMES = {
        "package.json", "package-lock.json", "yarn.lock", "pnpm-lock.yaml",
        "pyproject.toml", "setup.cfg", "setup.py", "poetry.lock",
        "Pipfile", "Pipfile.lock", "requirements.txt", "requirements-dev.txt",
        "pom.xml", "build.gradle", "build.gradle.kts", "settings.gradle",
        "Cargo.toml", "Cargo.lock", "go.mod", "go.sum",
        "Gemfile", "Gemfile.lock", "composer.json", "composer.lock",
        "Makefile", "CMakeLists.txt", "meson.build",
        "Dockerfile", "docker-compose.yml", "docker-compose.yaml",
        ".gitignore", ".gitattributes", ".editorconfig",
        ".eslintrc", ".prettierrc", ".babelrc",
        "tsconfig.json", "jsconfig.json", "jest.config.js", "jest.config.ts",
        "vitest.config.ts", "vitest.config.js",
        "next.config.mjs", "next.config.js", "vite.config.ts",
        ".importlinter",
    }

    # ── Documentation ─────────────────────────────────────────────────────────
    _DOC_EXTENSIONS  = {".md", ".rst", ".txt", ".adoc", ".tex"}
    _DOC_DIRS        = {"docs", "doc", "documentation", "wiki"}

    # ── Asset / binary files ──────────────────────────────────────────────────
    _ASSET_EXTENSIONS = {
        ".png", ".jpg", ".jpeg", ".gif", ".svg", ".ico", ".webp",
        ".pdf", ".mp4", ".mp3", ".wav",
        ".woff", ".woff2", ".ttf", ".eot",
        ".zip", ".tar", ".gz", ".7z",
        ".exe", ".dll", ".so", ".dylib",
        ".pyc", ".pyo", ".class", ".jar",
    }

    # ── Supported source languages ────────────────────────────────────────────
    _SOURCE_EXTENSIONS = {
        ".py", ".java",
        ".ts", ".tsx", ".js", ".jsx",
        ".go", ".rs",
        ".cpp", ".c", ".cc", ".h", ".hpp",
        ".cs", ".rb", ".kt", ".swift", ".scala",
        ".php", ".r",
    }

    def classify(self, path: str, first_line: str = "") -> ClassifiedFile:
        """Classify a single file path.

        Args:
            path:       relative path from repo root
            first_line: optional first line of file content for generated detection
        """
        parts = path.replace("\\", "/").split("/")
        filename = parts[-1]
        ext = ("." + filename.rsplit(".", 1)[-1].lower()) if "." in filename else ""

        # ── Check directory-level exclusions first ────────────────────────────
        for part in parts[:-1]:
            if part.lower() in self._VENDOR_DIRS:
                return ClassifiedFile(path, FileCategory.VENDOR, f"vendor directory: {part}")
            if part.lower() in self._BUILD_DIRS:
                return ClassifiedFile(path, FileCategory.BUILD, f"build directory: {part}")
            if part.lower() in self._SKIP_DIRS:
                return ClassifiedFile(path, FileCategory.BUILD, f"skip directory: {part}")
            if part.lower() in self._DOC_DIRS:
                return ClassifiedFile(path, FileCategory.DOCS, f"doc directory: {part}")

        # ── Assets ────────────────────────────────────────────────────────────
        if ext in self._ASSET_EXTENSIONS:
            return ClassifiedFile(path, FileCategory.ASSET, "binary/asset extension")

        # ── Config / lock files ───────────────────────────────────────────────
        if filename in self._CONFIG_FILENAMES:
            return ClassifiedFile(path, FileCategory.CONFIG, "known config filename")
        if filename.startswith(".") and ext in self._CONFIG_EXTENSIONS:
            return ClassifiedFile(path, FileCategory.CONFIG, "dotfile config")

        # ── Docs ──────────────────────────────────────────────────────────────
        if ext in self._DOC_EXTENSIONS:
            return ClassifiedFile(path, FileCategory.DOCS, "documentation extension")

        # ── Migrations ────────────────────────────────────────────────────────
        if self._MIGRATION_PATH_RE.search(path):
            return ClassifiedFile(path, FileCategory.MIGRATION, "migration directory pattern")
        if self._MIGRATION_FILE_RE.match(filename) and ext in (".py", ".sql", ".rb"):
            return ClassifiedFile(path, FileCategory.MIGRATION, "migration filename pattern (timestamped)")

        # ── Generated code (path-based) ───────────────────────────────────────
        if self._GENERATED_PATH_RE.search(path):
            return ClassifiedFile(path, FileCategory.GENERATED, "generated path pattern")
        if filename in self._GENERATED_FILENAMES:
            return ClassifiedFile(path, FileCategory.GENERATED, "known generated filename")
        # Generated code (content-based — first line hint)
        if first_line and self._GENERATED_COMMENT_RE.search(first_line):
            return ClassifiedFile(path, FileCategory.GENERATED, "generated file header comment")

        # ── Tests ─────────────────────────────────────────────────────────────
        if self._TEST_PATH_RE.search(path):
            return ClassifiedFile(path, FileCategory.TEST, "test directory pattern")
        if self._TEST_FILE_RE.search(path):
            return ClassifiedFile(path, FileCategory.TEST, "test filename pattern")

        # ── Source code ───────────────────────────────────────────────────────
        if ext in self._SOURCE_EXTENSIONS:
            return ClassifiedFile(path, FileCategory.SOURCE, "source code extension")

        # ── Unknown ───────────────────────────────────────────────────────────
        return ClassifiedFile(path, FileCategory.UNKNOWN, "no matching rule")

    def classify_many(
        self,
        paths_with_hints: list[tuple[str, str]],  # (path, first_line)
    ) -> list[ClassifiedFile]:
        return [self.classify(path, hint) for path, hint in paths_with_hints]
